const LISTS = {
    generic: {
        adjective: '/data/generic/adjective.json',
        allNoun: '/data/generic/all-noun.json',
        allNouns: '/data/generic/all-nouns.json',
        exclamation: '/data/generic/exclamation.json',
        noun: '/data/generic/noun.json',
        nouns: '/data/generic/nouns.json',
        preposition: '/data/generic/preposition.json',
        verb: '/data/generic/verb.json',
        verbed: '/data/generic/verbed.json',
        verbing: '/data/generic/verbing.json',
        verbs: '/data/generic/verbs.json',
        the: '/data/generic/the.json',
    },
    florida: {
        verb: '/data/florida/verb.json',
        endPhrase: '/data/florida/end-phrase.json',
        are: '/data/florida/are.json',
        locationTime: '/data/florida/location-time.json',
    },
    holiday: {
        spookyAdjective: '/data/holiday/spooky-adjective.json',
        spookyNoun: '/data/holiday/spooky-noun.json',
    },
    masonic: {
        adjective: '/data/masonic/adjective.json',
        noun: '/data/masonic/noun.json',
        of: '/data/masonic/of.json',
        ofthe: '/data/masonic/ofthe.json',
        preadjective: '/data/masonic/preadjective.json',
        prefix: '/data/masonic/prefix.json',
        suffix: '/data/masonic/suffix.json',
        title: '/data/masonic/title.json',
    },
    names: {
        firstName: '/data/names/first-name.json',
        lastName: '/data/names/last-name.json',
    },
    special: {
        catNames: '/data/special/cat-names.json',
        listOWords: '/data/special/list-o-words.json',
        videogames: '/data/special/videogames.txt',
        wordlabBands: '/data/special/wordlab-bands.json',
    },
    anime: {
        noun: '/data/anime/noun.json',
        nounPhrase: '/data/anime/noun-phrase.json',
        person: '/data/anime/person.json',
        adjective: '/data/anime/adjective.json',
        verb: '/data/anime/verb.json',
        verbed: '/data/anime/verbed.json',
        companion: '/data/anime/companion.json',
        location: '/data/anime/location.json',
        occasion: '/data/anime/occasion.json',
        purpose: '/data/anime/purpose.json',
        qualifier: '/data/anime/qualifier.json',
        personQualifier: '/data/anime/person-qualifier.json',
        name: '/data/anime/name.json',
    },
}

export { LISTS }
